/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DagsstatistikRouteImport } from './routes/dagsstatistik'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as SenasteRegistreringarRouteImport } from './routes/senaste-registreringar'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as VeckostatistikRouteImport } from './routes/veckostatistik'
import { Route as KategoriIdRouteImport } from './routes/kategori.$id'
import { Route as SummaryDayRouteImport } from './routes/summary.day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DagsstatistikRoute = DagsstatistikRouteImport.update({
  id: '/dagsstatistik',
  path: '/dagsstatistik',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const SenasteRegistreringarRoute = SenasteRegistreringarRouteImport.update({
  id: '/senaste-registreringar',
  path: '/senaste-registreringar',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const VeckostatistikRoute = VeckostatistikRouteImport.update({
  id: '/veckostatistik',
  path: '/veckostatistik',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIdRoute = KategoriIdRouteImport.update({
  id: '/kategori/$id',
  path: '/kategori/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryDayRoute = SummaryDayRouteImport.update({
  id: '/summary/day',
  path: '/summary/day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dagsstatistik': typeof DagsstatistikRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/promo': typeof PromoRoute
  '/senaste-registreringar': typeof SenasteRegistreringarRoute
  '/statistik': typeof StatistikRoute
  '/veckostatistik': typeof VeckostatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
  '/summary/day': typeof SummaryDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dagsstatistik': typeof DagsstatistikRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/promo': typeof PromoRoute
  '/senaste-registreringar': typeof SenasteRegistreringarRoute
  '/statistik': typeof StatistikRoute
  '/veckostatistik': typeof VeckostatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
  '/summary/day': typeof SummaryDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dagsstatistik': typeof DagsstatistikRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/promo': typeof PromoRoute
  '/senaste-registreringar': typeof SenasteRegistreringarRoute
  '/statistik': typeof StatistikRoute
  '/veckostatistik': typeof VeckostatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
  '/summary/day': typeof SummaryDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dagsstatistik'
    | '/historik'
    | '/installningar'
    | '/promo'
    | '/senaste-registreringar'
    | '/statistik'
    | '/veckostatistik'
    | '/kategori/$id'
    | '/summary/day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dagsstatistik'
    | '/historik'
    | '/installningar'
    | '/promo'
    | '/senaste-registreringar'
    | '/statistik'
    | '/veckostatistik'
    | '/kategori/$id'
    | '/summary/day'
  id:
    | '__root__'
    | '/'
    | '/dagsstatistik'
    | '/historik'
    | '/installningar'
    | '/promo'
    | '/senaste-registreringar'
    | '/statistik'
    | '/veckostatistik'
    | '/kategori/$id'
    | '/summary/day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DagsstatistikRoute: typeof DagsstatistikRoute
  HistorikRoute: typeof HistorikRoute
  InstallningarRoute: typeof InstallningarRoute
  PromoRoute: typeof PromoRoute
  SenasteRegistreringarRoute: typeof SenasteRegistreringarRoute
  StatistikRoute: typeof StatistikRoute
  VeckostatistikRoute: typeof VeckostatistikRoute
  KategoriIdRoute: typeof KategoriIdRoute
  SummaryDayRoute: typeof SummaryDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dagsstatistik': {
      id: '/dagsstatistik'
      path: '/dagsstatistik'
      fullPath: '/dagsstatistik'
      preLoaderRoute: typeof DagsstatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senaste-registreringar': {
      id: '/senaste-registreringar'
      path: '/senaste-registreringar'
      fullPath: '/senaste-registreringar'
      preLoaderRoute: typeof SenasteRegistreringarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veckostatistik': {
      id: '/veckostatistik'
      path: '/veckostatistik'
      fullPath: '/veckostatistik'
      preLoaderRoute: typeof VeckostatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$id': {
      id: '/kategori/$id'
      path: '/kategori/$id'
      fullPath: '/kategori/$id'
      preLoaderRoute: typeof KategoriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/day': {
      id: '/summary/day'
      path: '/summary/day'
      fullPath: '/summary/day'
      preLoaderRoute: typeof SummaryDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DagsstatistikRoute: DagsstatistikRoute,
  HistorikRoute: HistorikRoute,
  InstallningarRoute: InstallningarRoute,
  PromoRoute: PromoRoute,
  SenasteRegistreringarRoute: SenasteRegistreringarRoute,
  StatistikRoute: StatistikRoute,
  VeckostatistikRoute: VeckostatistikRoute,
  KategoriIdRoute: KategoriIdRoute,
  SummaryDayRoute: SummaryDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
