/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as VeckostatistikRouteImport } from './routes/veckostatistik'
import { Route as KategoriIdRouteImport } from './routes/kategori.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const VeckostatistikRoute = VeckostatistikRouteImport.update({
  id: '/veckostatistik',
  path: '/veckostatistik',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIdRoute = KategoriIdRouteImport.update({
  id: '/kategori/$id',
  path: '/kategori/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/installningar': typeof InstallningarRoute
  '/statistik': typeof StatistikRoute
  '/veckostatistik': typeof VeckostatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/installningar': typeof InstallningarRoute
  '/statistik': typeof StatistikRoute
  '/veckostatistik': typeof VeckostatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/installningar': typeof InstallningarRoute
  '/statistik': typeof StatistikRoute
  '/veckostatistik': typeof VeckostatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/installningar' | '/statistik' | '/veckostatistik' | '/kategori/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/installningar' | '/statistik' | '/veckostatistik' | '/kategori/$id'
  id:
    | '__root__'
    | '/'
    | '/installningar'
    | '/statistik'
    | '/veckostatistik'
    | '/kategori/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallningarRoute: typeof InstallningarRoute
  StatistikRoute: typeof StatistikRoute
  VeckostatistikRoute: typeof VeckostatistikRoute
  KategoriIdRoute: typeof KategoriIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veckostatistik': {
      id: '/veckostatistik'
      path: '/veckostatistik'
      fullPath: '/veckostatistik'
      preLoaderRoute: typeof VeckostatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$id': {
      id: '/kategori/$id'
      path: '/kategori/$id'
      fullPath: '/kategori/$id'
      preLoaderRoute: typeof KategoriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallningarRoute: InstallningarRoute,
  StatistikRoute: StatistikRoute,
  VeckostatistikRoute: VeckostatistikRoute,
  KategoriIdRoute: KategoriIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
