/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as KategoriIdRouteImport } from './routes/kategori.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIdRoute = KategoriIdRouteImport.update({
  id: '/kategori/$id',
  path: '/kategori/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/statistik': typeof StatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statistik': typeof StatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/statistik': typeof StatistikRoute
  '/kategori/$id': typeof KategoriIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/statistik' | '/kategori/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/statistik' | '/kategori/$id'
  id: '__root__' | '/' | '/statistik' | '/kategori/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatistikRoute: typeof StatistikRoute
  KategoriIdRoute: typeof KategoriIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$id': {
      id: '/kategori/$id'
      path: '/kategori/$id'
      fullPath: '/kategori/$id'
      preLoaderRoute: typeof KategoriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatistikRoute: StatistikRoute,
  KategoriIdRoute: KategoriIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
